version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
      
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: git submodule update --init

      - run: yarn install
      - run: cd frontend && yarn install
      - run: cd backend && yarn install
      - run: yarn test

      - run:
          name: "Install wine"
          command: |
            sudo add-apt-repository -y ppa:ubuntu-wine/ppa
            sudo apt-get update
            sudo apt-get install -y wine

      - run: yarn run build:full
      - run: cd build && for i in */; do zip -r -rm "${i%/}.zip" "$i"; done
      
      - store_artifacts:
          path: build
      





