version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
      
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: git submodule update --init

      - run: yarn install
      - run: cd frontend && yarn install
      - run: cd backend && yarn install
      - run: yarn test

      - run: yarn run build
      - run: mv ./dist/*.dmg ./build
      
      - store_artifacts:
          path: build
      





