version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
      
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: git submodule update --init

      - run: yarn install
      - run: cd frontend && yarn install
      - run: cd backend && yarn install
      - run: yarn test
      - run: yarn run build:full:osx
      - run: cd build && for i in */; do zip -r -rm "${i%/}.zip" "$i"; done
      
      - store_artifacts:
          path: build
      





